name: eclub_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.0
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.9+2  
  mobile_scanner: ^4.0.0
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.8
  camera: ^0.11.0
  path_provider: ^2.0.15
  http: ^1.2.1
  location: ^5.0.3
  geocoding: ^2.1.1
  record: any
  tflite_flutter: ^0.11.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  another_telephony: any
  flutter_local_notifications: ^17.0.0
  # workmanager: ^0.5.1  <-- REMOVED

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image_6d3861.png
    - assets/ml/model.tflite
    - assets/ml/labels.txt
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    - family: Overpass Mono
      fonts:
        - asset: assets/fonts/OverpassMono.ttf
    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta.ttf